### ISSUE TITLE
type mismatch on syntex::Registry on nightly

### ISSUE THREAD

**Issue by sourcefrog** [erickt/rust-quasi#15]
rustc 1.5.0-nightly (20a6938c0 2015-10-16)

```
/Users/mbp/.multirust/toolchains/nightly/cargo/registry/src/github.com-0a35038f75765ae4/quasi_macros-0.3.4/src/lib.rs:19:29: 19:32 error: mismatched types:
 expected `&mut syntex::Registry`,
    found `&mut rustc::plugin::registry::Registry<'_>`
(expected struct `syntex::Registry`,
    found struct `rustc::plugin::registry::Registry`) [E0308]
/Users/mbp/.multirust/toolchains/nightly/cargo/registry/src/github.com-0a35038f75765ae4/quasi_macros-0.3.4/src/lib.rs:19     quasi_codegen::register(reg);
                                                                                                                                                     ^~~
/Users/mbp/.multirust/toolchains/nightly/cargo/registry/src/github.com-0a35038f75765ae4/quasi_macros-0.3.4/src/lib.rs:19:29: 19:32 help: run `rustc --explain E0308` to see a detailed explanation
```

**Comment by erickt** [comment]
I just pushed an updated quasi. Want to try again?

**Comment by sourcefrog** [comment]
It works when I build the v0.3.5 tag of quasi macros in its own tree.

When cargo builds this, from `google-apis-rs`, even after a `cargo clean`, I'm still seeing:

```
   Compiling quasi_macros v0.3.5
/Users/mbp/.multirust/toolchains/nightly/cargo/registry/src/github.com-0a35038f75765ae4/quasi_macros-0.3.5/src/lib.rs:19:29: 19:32 error: mismatched types:
 expected `&mut syntex::Registry`,
    found `&mut rustc::plugin::registry::Registry<'_>`
(expected struct `syntex::Registry`,
    found struct `rustc::plugin::registry::Registry`) [E0308]
/Users/mbp/.multirust/toolchains/nightly/cargo/registry/src/github.com-0a35038f75765ae4/quasi_macros-0.3.5/src/lib.rs:19     quasi_codegen::register(reg);
                                                                                                                                                     ^~~
/Users/mbp/.multirust/toolchains/nightly/cargo/registry/src/github.com-0a35038f75765ae4/quasi_macros-0.3.5/src/lib.rs:19:29: 19:32 help: run `rustc --explain E0308` to see a detailed explanation
error: aborting due to previous error
Build failed, waiting for other jobs to finish...
Could not compile `quasi_macros`.
```

**Comment by erickt** [comment]
This is a google-apis-rs bug. I fixed it in https://github.com/Byron/google-apis-rs/pull/132.
