### ISSUE TITLE
quasi_codegen compile error

### ISSUE THREAD

**Issue by rschulman** [erickt/rust-quasi#20]
I get the following error when compiling quasi_codegen (included from serde) on rustc 1.6.0-nightly (b7845f93b 2015-11-15)

```
586:39 error: no method named `parse_expr_panic` found for type `syntax::parse::parser::Parser<'_>` in the current scope
```

**Comment by sorccu** [comment]
Caused by rust-lang/rust@44d8abcc0f372dbc7ad58f312303d2e59612dec9, looks to me like replacing `parse_expr_panic()` with `parse_expr().unwrap()` would accomplish the same thing.

**Comment by rusty-new-dev** [comment]
I get the same error on 1.4 stable. If I replace it with `parse_expr().unwrap()`, serde_codegen fails to build with more errors that are similar.

**Comment by gregkatz** [comment]
I was able to get some success fixing this by running cargo clean and removing my Cargo.lock, and rebuilding.

On second thought, I'm not sure how I fixed it. I can't reproduce it.

**Comment by rusty-new-dev** [comment]
with a recent nightly `rustc 1.6.0-nightly (a7644b33d 2015-11-17)`, I'm still seeing this error with quasi_codegen v0.3.7.

**Comment by rusty-new-dev** [comment]
I'm not sure if it's the right change but I was able to get it compiling and compiled serde_codegen successfully with this change: https://github.com/rusty-new-dev/quasi/commit/79c364c31548a6207c1f451a3a4c46528d374fc5

**Comment by erickt** [comment]
quasi is back to compiling in 0.3.8!
